### ISSUE TITLE
skip button not appearing

### ISSUE THREAD

**Issue by badrizahra** [DoomTay/videojs-vast-vpaid-waterfall#1]
i add skip button in vast xml and check my xml with online vast validator and that's ok.
but it doesnt work in my sample code. what's wrong??!!
my skip button doesnt appear in my ads video.
i can not find the reason.

**Comment by DoomTay** [comment]
At the moment, the plugin doesn't support skip button implementation

Can you post the full sample tag so I can test it?

**Comment by badrizahra** [comment]
[videojs-vast-vpaid-waterfall-master.zip](https://github.com/DoomTay/videojs-vast-vpaid-waterfall/files/2195465/videojs-vast-vpaid-waterfall-master.zip)

thanks for your comment . i put it here.
is there a way or a plugin that support all of the vast xml tags ?

**Comment by badrizahra** [comment]
thanks so much 👍 :)
