### ISSUE TITLE
Preroll on live videos does not work

### ISSUE THREAD

**Issue by Jaluco** [DoomTay/videojs-vast-vpaid-waterfall#5]
I get the error 
`VIDEOJS: ERROR: TypeError: Cannot read property 'suppressedTracks' of undefined`
when attempting to end the preroll and going back to the stream.

**Comment by DoomTay** [comment]
This might be on the videojs-contrib-ads library. Do you have an example ad set?

**Comment by Jaluco** [comment]
Yes, I use the same example set you use in this repository, the problem is after the preroll the livestream does not start.

**Comment by DoomTay** [comment]
Well whaddya know, it IS on the videojs-contrib-ads library, at least with permissions set to block audio. Thankfully, updating from 6.3.0 to, say, 6.6.5 remedies this

**Comment by Jaluco** [comment]
I'm sorry, I'm new to videojs and do not understand what you mean. Updating videojs-contrib-ads did not help :(

**Comment by Jaluco** [comment]
Managed to fix the problem, thanks :)

**Comment by charliefancelli** [comment]
@Jaluco can you explain your fix please ?
